### ISSUE TITLE
cookie size changed to 259 bytes

### ISSUE THREAD

**Issue by mvk** [adrienverge/openfortivpn#32]
I've seen some follow ups, used their ideas and it works.

**Comment by adrienverge** [comment]
Thanks @mvk. Pull request #31 should fix this, feel free to test and feedback!

**Comment by mvk** [comment]
I'm still having issue with:
FortiWiFi-60D International, v5.2.3,build670 (GA)
I'll close this one though.
